//! Export per-sample multi-head mismatches vs gold (special_type + variation).
//!
//! cargo run --manifest-path tamil-seiyul-alagi/Cargo.toml --example export_sample_mismatches

use std::fs;
use std::path::PathBuf;

use thepulimaangani_parser::{
    gold_metre_type_for_parent, parse_poem, poem_variation_label_rows, MetreType, ParseOptions,
};

fn label_of(m: &MetreType) -> String {
    match m {
        MetreType::Venpaa => "Venpaa".into(),
        MetreType::Aciriyappaa => "Aciriyappaa".into(),
        MetreType::Kalippaa => "Kalippaa".into(),
        MetreType::Vanjippaa => "Vanjippaa".into(),
        MetreType::Other(s) => s.clone(),
    }
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../data/training/reports");
    fs::create_dir_all(&root)?;
    let labels = poem_variation_label_rows();
    let mut rows = Vec::new();
    let mut mismatch_md = String::from(
        "# Sample mismatch list (ML heads vs gold)\n\n\
         Generated by `export_sample_mismatches`.\n\n\
         ## Honesty note (in-sample vs ADOPT)\n\n\
         Live multi-head votes (`dense_logistic`, `prototype_knn`) are fitted on the full \
         **special_type** anthology. Parsing those poems is **in-sample** for those heads — \
         head agreement is useful UX comparison, **not** held-out ADOPT evidence. \
         The primary-path **baseline freeze** (heuristic/hybrid on special_type with Monte Carlo) \
         remains the right ADOPT gate. **variation** rows are stress-only.\n\n\
         | sample_id | kind | gold | hybrid/heuristic | dense_logistic | prototype_knn | hybrid_ok | logistic_ok | proto_ok |\n\
         |-----------|------|------|------------------|----------------|---------------|-----------|-------------|----------|\n",
    );
    let mut mismatches = Vec::new();

    for label in &labels {
        let r = match parse_poem(&label.text, ParseOptions::default()) {
            Ok(r) => r,
            Err(_) => continue,
        };
        let Some(g) = gold_metre_type_for_parent(&label.parent_metre) else {
            continue;
        };
        let gold = label_of(&g);
        let hybrid = r
            .metre_type
            .as_ref()
            .map(label_of)
            .unwrap_or_else(|| "?".into());
        let ml = r.metre_ml.as_ref();
        let mut logistic = "—".to_string();
        let mut proto = "—".to_string();
        let mut logistic_score = None;
        let mut proto_score = None;
        if let Some(m) = ml {
            for h in &m.head_votes {
                if h.head_id == "dense_logistic" {
                    logistic = h.metre_type.clone();
                    logistic_score = Some(h.score);
                }
                if h.head_id == "prototype_knn" {
                    proto = h.metre_type.clone();
                    proto_score = Some(h.score);
                }
            }
        }
        let hybrid_ok = hybrid == gold;
        let logistic_ok = logistic == gold;
        let proto_ok = proto == gold;
        let any_mismatch = !(hybrid_ok && logistic_ok && proto_ok);
        let row = serde_json::json!({
            "sample_id": label.sample_id,
            "row_kind": label.row_kind,
            "parent_metre": label.parent_metre,
            "gold": gold,
            "hybrid": hybrid,
            "dense_logistic": logistic,
            "dense_logistic_score": logistic_score,
            "prototype_knn": proto,
            "prototype_knn_score": proto_score,
            "hybrid_ok": hybrid_ok,
            "logistic_ok": logistic_ok,
            "proto_ok": proto_ok,
            "any_mismatch": any_mismatch,
            "classical_ok_for_ml_top": ml.and_then(|m| m.dual_truth.classical_ok_for_ml_top),
            "classical_violations": ml.map(|m| m.dual_truth.classical_violations.clone()).unwrap_or_default(),
        });
        rows.push(row);
        if any_mismatch {
            mismatch_md.push_str(&format!(
                "| {} | {} | {} | {} | {} | {} | {} | {} | {} |\n",
                label.sample_id,
                label.row_kind,
                gold,
                hybrid,
                logistic,
                proto,
                hybrid_ok,
                logistic_ok,
                proto_ok
            ));
            mismatches.push(serde_json::json!({
                "sample_id": label.sample_id,
                "row_kind": label.row_kind,
                "gold": gold,
                "hybrid": hybrid,
                "dense_logistic": logistic,
                "prototype_knn": proto,
            }));
        }
    }

    let summary = serde_json::json!({
        "n_total": rows.len(),
        "n_mismatch_any_head": mismatches.len(),
        "n_hybrid_mismatch": rows.iter().filter(|r| r["hybrid_ok"] == false).count(),
        "n_logistic_mismatch": rows.iter().filter(|r| r["logistic_ok"] == false).count(),
        "n_proto_mismatch": rows.iter().filter(|r| r["proto_ok"] == false).count(),
        "mismatches": mismatches,
        "all_rows": rows,
    });
    fs::write(
        root.join("sample_mismatches.json"),
        serde_json::to_string_pretty(&summary)?,
    )?;
    if mismatches.is_empty() {
        mismatch_md.push_str("\n_No multi-head mismatches on this corpus slice._\n");
    }
    mismatch_md.push_str(&format!(
        "\n## Counts\n\n- total samples: {}\n- any-head mismatch: {}\n- hybrid≠gold: {}\n- logistic≠gold: {}\n- proto≠gold: {}\n",
        summary["n_total"],
        summary["n_mismatch_any_head"],
        summary["n_hybrid_mismatch"],
        summary["n_logistic_mismatch"],
        summary["n_proto_mismatch"],
    ));
    fs::write(root.join("sample_mismatches.md"), mismatch_md)?;
    println!(
        "wrote sample_mismatches.md/json (total={}, any_mismatch={})",
        summary["n_total"], summary["n_mismatch_any_head"]
    );
    Ok(())
}
