/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutTimelineRouteImport } from './routes/about.timeline'
import { Route as AboutHistoryRouteImport } from './routes/about.history'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutTimelineRoute = AboutTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AboutRoute,
} as any)
const AboutHistoryRoute = AboutHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AboutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/about/history': typeof AboutHistoryRoute
  '/about/timeline': typeof AboutTimelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/about/history': typeof AboutHistoryRoute
  '/about/timeline': typeof AboutTimelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/about/history': typeof AboutHistoryRoute
  '/about/timeline': typeof AboutTimelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/about/history' | '/about/timeline'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/about/history' | '/about/timeline'
  id: '__root__' | '/' | '/about' | '/about/history' | '/about/timeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/timeline': {
      id: '/about/timeline'
      path: '/timeline'
      fullPath: '/about/timeline'
      preLoaderRoute: typeof AboutTimelineRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/history': {
      id: '/about/history'
      path: '/history'
      fullPath: '/about/history'
      preLoaderRoute: typeof AboutHistoryRouteImport
      parentRoute: typeof AboutRoute
    }
  }
}

interface AboutRouteChildren {
  AboutHistoryRoute: typeof AboutHistoryRoute
  AboutTimelineRoute: typeof AboutTimelineRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutHistoryRoute: AboutHistoryRoute,
  AboutTimelineRoute: AboutTimelineRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
